### ISSUE TITLE
[Feature Request] Always show input box

### ISSUE THREAD

**Issue by AndyLiu9** [vrtmrz/ob-w-kbd#1]
I read your post from Obsidian forum and thanks for your simple but effective plugin. Currently after pressing Enter, the box is closed. Is there any possibility to add a command to always show the input box?

**Comment by vrtmrz** [comment]
Thank you for trying this plugin. I'm also troubled too.
I have added this feature and a little more along with bug fixes. I hope this feature works for you too.

**Comment by AndyLiu9** [comment]
Thanks!
